### ISSUE TITLE
Python 3.8 support?

### ISSUE THREAD

**Issue by Pikamander2** [lobe/lobe-python#20]
Is there an ETA for when Python 3.8 will be supported? Tensorflow [supports](https://www.tensorflow.org/install/pip) Python 3.8 now, so it would be nice to be able to use it.

**Comment by mbeissinger** [comment]
3.8 should work fine, are you seeing an error?

**Comment by Pikamander2** [comment]
Oh cool. I hadn't actually tried it with 3.8 because the readme said to use 3.7. I'll make a pull request for that.

**Comment by averypfeiffer** [comment]
Can confirm. I've been using it with python 3.8 for a few weeks now. No problem.

**Comment by Pikamander2** [comment]
I ran into one error on Windows ('python3' is not recognized as an internal or external command, operable program or batch file.) but otherwise it seems to work fine with Python 3.8.

Here's a pull request to update the docs.

**Comment by mbeissinger** [comment]
@Pikamander2  Yep I would highly recommend using a virtual environment (python -m venv .venv) so that anything pip3 just becomes pip -- you have to create the virtual environment with the right python being called, so on windows you can do something like:
`C:\Python38\python.exe -m venv .venv` and now when you activate the environment with `.venv\Scripts\activate` every command related to python (so `python` and `pip`) will reference that local environment. More info here: https://docs.python.org/3/tutorial/venv.html

**Comment by mbeissinger** [comment]
I'll actually add a bit to the readme about the details for virtual environment and that it should support python 3.6-3.8, so will abandon #21  for now

**Comment by mikematas** [comment]
Finally closed!

>

**Comment by mbeissinger** [comment]
@mikematas lol yeah forgot it was still open, no code changes needed XD
